//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjSighUp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TableMembers1092034
    {
        [DisplayName("會員編號")]
        [Required(ErrorMessage = "會員編號不可空白")]
        [StringLength(4, ErrorMessage = "員工編號必須是4個字元")]
        public string mId { get; set; }

        [DisplayName("會員姓名")]
        [Required(ErrorMessage = "姓名不可空白")]
        public string mName { get; set; }

        [DisplayName("帳號")]
        [Required(ErrorMessage = "帳號不可空白")]
        [StringLength(10, ErrorMessage = "帳號必須是10個數字和英文")]
        public string account { get; set; }

        [DisplayName("密碼")]
        [Required(ErrorMessage = "密碼不可空白")]
        public string password { get; set; }

        [DisplayName("手機")]
        public string phone { get; set; }

        [DisplayName("活動編號")]
        public string aNo { get; set; }
    
        public virtual TableActivitys1092034 TableActivitys1092034 { get; set; }
    }
}
