//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjSighUp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TableActivitys1092034
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableActivitys1092034()
        {
            this.TableMembers1092034 = new HashSet<TableMembers1092034>();
        }
        [DisplayName("活動編號")]
        [Required(ErrorMessage = "活動編號不可空白")]
        [StringLength(4, ErrorMessage = "活動編號必須是4個字元")]
        public string aNo { get; set; }

        [DisplayName("活動名稱")]
        [Required(ErrorMessage = "活動名稱不可空白")]
        public string aName { get; set; }

        [DisplayName("性質")]
        [Required(ErrorMessage = "活動性質不可空白")]
        [StringLength(8, ErrorMessage = "活動編號必須是兩個字")]
        public string nature { get; set; }

        [DisplayName("性質編號")]
        [Required(ErrorMessage = "性質編號不可空白")]
        [StringLength(1, ErrorMessage = "為1個字元，需對應活動性質")]
        public string natureNo { get; set; }

        [DisplayName("開始日期")]
        [Required(ErrorMessage = "開始日期不可空白")]
        public System.DateTime date { get; set; }

        [DisplayName("開始時間")]
        [Required(ErrorMessage = "開始時間不可空白")]
        public string time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableMembers1092034> TableMembers1092034 { get; set; }
    }
}
